version: '3.8'

services:
  app:
    build: .
    container_name: order-service-app
    ports:
      - "5001:5000"
    environment:
      - HOST=0.0.0.0
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=orderdb
      - DB_PORT=5432
    depends_on:
      - db
    restart: on-failure
    networks:
      - order-network

  db:
    image: postgres:14-alpine
    container_name: order-service-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orderdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - order-network

networks:
  order-network:
    driver: bridge

volumes:
  postgres_data:
